# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efd2a9b090bebb11a122a191772336cd20f36b6a489df9c42c4510273f98ca1072a555740d28e1858f5c82a9c17d870d2ce4bf267918d88250f45041f1cebb1c

test:
  secret_key_base: 6fcd6e1749ae7c346b19ab771fd00c0d556d4753ec399404d9aab662ec211732396414762fd7782707b9cda10d835f5546eb8cada32e42bbc1be9d1d32cf5d38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
